[versions]
agp = "8.13.1"
core = "3.5.4"
#junit = "4.13.2"
#junitVersion = "1.3.0"
#espressoCore = "3.7.0"
appcompat = "1.7.1"
#activity = "1.12.0"
uiAndroid = "1.9.5"
#material = "1.13.0"

[libraries]
core = { module = "com.google.zxing:core", version.ref = "core" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }